### ISSUE TITLE
auth not working

### ISSUE THREAD

**Issue by nakidong** [Khezen/docker-mongo-rocks#1]
https://github.com/Khezen/docker-mongo/blob/master/entrypoint.sh#L68

i think this will change to

if [ ! -f "$dbpath"/.mongodb_password_set ] && [ "$auth" == "y" ]; then

**Comment by nakidong** [comment]
i found a misspelling with this line.

https://github.com/Khezen/docker-mongo/blob/master/entrypoint.sh#L64

**Comment by khezen** [comment]
Thank you for reporting. I have some issues with my keyboard so there isn't much I can do until I get my new laptop. I'll fix this issue on Monday or Tuesday depending on that delivery.
Thanks again.

**Comment by Khezen** [comment]
auth should be working for standalone and replica set configuration. I am still working on sharded cluster support.

**Comment by Khezen** [comment]
auth should be working with standalone and replica set configurations. I am still working on support for sharded cluster.

**Comment by khezen** [comment]
I updated the code and pushed the image to its docker registry. Please tell me if you have any issue with the new image.

**Comment by khezen** [comment]
Without any news from you I am closing this issue.
