### ISSUE TITLE
Getting ERROR: Version in "./docker-compose.yml" is unsupported.

### ISSUE THREAD

**Issue by usamaB** [Khezen/docker-mongo-rocks#18]
> ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key or omit the `version` key and place your service definitions at the root of the file to use version 1.

Docker version 17.06.0-ce, build 02c1d87 
docker-compose version 1.8.0, build unknown

Even if I erase everything in the file and just let the first line "version" in there it still gives the same error.

**Comment by khezen** [comment]
can you provide your dokcer-compose.yml?

**Comment by usamaB** [comment]
Basically the one  in the swarm folder 


[docker-compose.txt](https://github.com/Khezen/docker-mongo/files/1207845/docker-compose.txt)

**Comment by usamaB** [comment]
`asda`

**Comment by usamaB** [comment]
Basically the one  in the swarm folder 
`version: '3'

services:

  replica1:
    image: khezen/mongo:slim
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      palcement:
        node.hostname: node-1
    environment:
      RS_NAME: shard1
      AUTH: 'y'
    volumes:
      - /data/mongo/replica1:/data/db
    networks:
      - mongo_cluster

  replica2:
    image: khezen/mongo:slim
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      palcement:
        node.hostname: node-2
    environment:
      RS_NAME: shard1
      AUTH: 'y'
    volumes:
      - /data/mongo/replica2:/data/db
    networks:
      - mongo_cluster

  replica3:
    image: khezen/mongo:slim
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      palcement:
        node.hostname: node-3
    environment:
      RS_NAME: shard1
      MASTER: replica3
      SLAVES: replica1 replica2
      AUTH: 'y'
    volumes:
      - /data/mongo/replica3:/data/db
    networks:
      - mongo_cluster

networks:
  mongo_cluster:
    driver: overlay`

**Comment by khezen** [comment]
Unable to reproduce.

@usamaB please upgrade docker-compose to latest release.

**Comment by usamaB** [comment]
thanks, 
the errors are gone. I had to update a couple of things, but how long does it take to run, it took like 40 mins ... 
Docker version 17.06.0-ce, build 02c1d87
docker-compose version 1.15.0, build e12f3b9
@Khezen  is this normal?
