### ISSUE TITLE
how do I specify priority in docker compose

### ISSUE THREAD

**Issue by wanglinsong** [Khezen/docker-mongo-rocks#24]
I have a mongo cluster of 3 nodes, node1, node2, and node3.
I want to start all 3 in a compose file, and make node1 has priority 3, node2 has priority 2, and node3 has priority 1. How can I do this in compose file?

**Comment by khezen** [comment]
It is not possible at the moment. The initial master node is set with higher priority by default and it is not possible to change it without going through a mongo client. This is something I need to change when I'll have time.

**Comment by khezen** [comment]
The image has been refactored completely to be more simple to use. I drop support for releases lower than mongo 3.6.2.

You should not experience any problem about setting priority with the latest image.

If you experience problems with the 3.6 or above, please reports in a new issue.
